### ISSUE TITLE
how set user and group for mounted ftp volume???

### ISSUE THREAD

**Issue by cocodrino** [Valuya/docker-volume-curlftpfs#3]
Hi, good day, I'm trying to mount the unit as a specific user, I tried this

```
docker volume create -d valuya/curlftpfs:next -o address=ftp.livedrive.com credentials=qqq@zzz.com:i12345 -o uid=33 -o gid=0  ftpvolume2


```

but I get

Error response from daemon: create ftpvolume2: VolumeDriver.Create: unknown option "0"

and if delete the gid parameter I get 

Error response from daemon: create ftpvolume2: VolumeDriver.Create: unknown option "33"

seems than uid and gid parameters are not permited...how can achieve this???...thank you!!!

**Comment by cghislai** [comment]
hi currently, the volume is mounted with the following options: allow_other,uid=1000,gid=1000,umask=0022.
The allow_other flag should allow any user to access the files.

I keep this issue open to allow to specify the mount options as plugin parameters.

**Comment by cocodrino** [comment]
thank you so much, we really need this option, another question, how is the performance/stability compared to sshfs???...we don't care so much the encryption so plain ftp is ok for us but we need pass a lot of data all the time to one mounted folder, do you think than this is a good option???...thank you!!!

**Comment by ymajoros** [comment]
I wouldn't expect too much performance from ftp. I don't think that ssh will make a big overhead, so it should be in the same category anyway. If you really need performance, I'd go to distributed filesystems like glusterfs. ceph, ...

**Comment by cghislai** [comment]
The plugin basically calls curlftpfs to mount the ftp volume when required.
I don't have much experience with this plugin yet as it is not yet deployed
in our production.
However, I experienced some instability using an externally mounted ftp
volume using curlftpfs from a dockerized application. The files were
visible from the host, but not from the container anymore (i haven't found
the root cause yet). To work around this issue, you may add an health check
in your dockerized service, so that containers are restarted when to ftp
volume is empty.

I expect to work on this by the end of the year. Hopefully I'll have more
feedback for you by then.

**Comment by cghislai** [comment]
you can now use the uid/gid options starting from valuya/curlftpfs:2
